[package]
name = "DNP3Attacks"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
dnp3 = "1.6.0"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0.98"